default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: arsh
  password: password123
  host: localhost

development:
  <<: *default
  database: book_nook_wpg_development

test:
  <<: *default
  database: book_nook_wpg_test

production:
  <<: *default
  database: book_nook_wpg_production
  username: arsh
  password: <%= ENV["BOOK_NOOK_WPG_DATABASE_PASSWORD"] %>
